xtclsh build-project.tcl invaders_papilio_duo_lx9_computing_shield.xise
copy build\invaders_top.bit bit_files\XC6SLX9-DUO\invaders.bit
copy source\invaders_bd.bmm bit_files\XC6SLX9-DUO\invaders_bd.bmm
xtclsh build-project.tcl invaders_papilio_pro_lx9_Arcade_MegaWing.xise
copy build\invaders_top.bit bit_files\XC6SLX9-PRO\invaders.bit
copy source\invaders_bd.bmm bit_files\XC6SLX9-PRO\invaders_bd.bmm
xtclsh build-project.tcl invaders_papilio_one_500k_Arcade_MegaWing.xise
copy build\invaders_top.bit bit_files\XC3S500E\invaders.bit
copy source\invaders_bd.bmm bit_files\XC3S500E\invaders_bd.bmm
